import s from './NotFoundPage.module.css'

function NotFoundPage() {
  return (
    <main className={s.notfoundpage_wrapper}>
     <h1 onLoad={() => this.scrollIntoView({block: 'end'})}>This page has no content related to my works or blog.</h1>
     <h2>It contains only this picture generated by YandexGPT</h2>
     <div className={s.notfound_picture}></div>
     <h2>The menu above will return you to the human world.</h2>
    </main>
  )
}

export default NotFoundPage